change workflow regarding to black

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -9,12 +9,18 @@ jobs:
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v3
-      - name: Black
-        uses: microsoft/action-python@0.7.0
+      - name: Set up Python 3.9
+        uses: actions/setup-python@v3
         with:
-          python_version: 3.9
-          black: true
-          workdir: .
+          python-version: 3.9
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+      - name: Linting with black
+        run: |
+          black --check .
+          exit $? # exit with the return code of the previous command
           
   build-and-coverage:
     runs-on: ubuntu-20.04
